### ISSUE TITLE
Ajout de Scss à React

### ISSUE THREAD

**Issue by t1gu1** [t1gu1/tp-goodfood#14]

**Comment by crimsloth** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/66810754/88592400-f58c3880-d02b-11ea-9d97-bde1c7dd72af.png)

**Comment by crimsloth** [comment]
Je crois que j'ai réussi à installer scss.

**Comment by t1gu1** [comment]
Je ne vois rien dans les dépendances du package.json
Lorsque tu fais le `npm install node-sass --save`, assure toi de mettre --save afin qu'il soit ajouté dans le package.json.

Peut-être t'as juste rien commit aussi?

**Comment by crimsloth** [comment]
non j'avais juste join la photo, je peux commit si tu veux

**Comment by crimsloth** [comment]
j'ai fais le commit.

**Comment by t1gu1** [comment]
Good!

Maintenant que j'y pense, question d'avoir une petite base, peux-tu créer le dossier `src/assets` et y créer les fichiers .scss suivants:

- global.scss
- vars.scss
- function.scss
- mixins.scss
- main.scss

Ensuite faire un import des fichiers (Tout sauf main.scss):
- global.scss
- vars.scss
- function.scss
- mixins.scss

Dans `main.scss`.

**Comment by crimsloth** [comment]
J'ai commit incluant le edit pour ajouter les fichiers et les imports.

**Comment by t1gu1** [comment]
Finalement, fait comme on a jaser dans messenger.

> En bref, global.scss va être un fichier que tu vas pouvoir directement importer dans ton fichier html genre. Alors que "main.scss" renommé en "_utils.scss" va être importer dans la feuille de style de tes composants.

**Comment by crimsloth** [comment]
j'ai commit les modifications suite à notre conversation sur messenger.
