### ISSUE TITLE
Récupération des images/assets necessaire sur le site de goodfood

### ISSUE THREAD

**Issue by t1gu1** [t1gu1/tp-goodfood#15]
Crée-toi un dossier `src/assets/img` s'il n'y en a pas déjà un et ajoute y les images et assets nécessaire.

**Comment by t1gu1** [comment]
Juste pour faire un up, j’ai changé il y a quelques heures la description de la tâche pour ajouter un point un peu plus précis.

**Comment by t1gu1** [comment]
Je ne vois aucune image dans le git

**Comment by t1gu1** [comment]
Dans un même temps, peux-tu créer un dossier pour le style.
`src/assets/scss` et mettre les fichiers de style à l'intérieur.

**Comment by t1gu1** [comment]
Je ne vois pas le dossier suivant: `src/assets/img` et je ne vois aucune images dans le projet sur le git.
P.S. toujours pousser les trucs en lien avec le billet sur le git afin que je puisse vérifier.

**Comment by crimsloth** [comment]
Je les avais mis à la source (tp-goodfood/src/Documents/images/PNG/) avec les liens des images, mais je vais les déplacer comme tu dis.

**Comment by t1gu1** [comment]
Haa ok je viens de voir

Déplaces les fonts dans assets aussi
`src/assets/fonts`

**Comment by t1gu1** [comment]
Autre point, pour le nom de tes dossier et de tes fichiers, utilises toujours des - pour la séparation entre les mots et aucune majuscule. Le point principale de ça, c'est que c'est meilleure pour le référencement.

**Comment by crimsloth** [comment]
Fait

**Comment by t1gu1** [comment]
T'as encore des fichier avec des `_`qui sont à remplacer par des `-`.
Il y a encore des dossiers avec des **M**ajususcules.

**Comment by crimsloth** [comment]
mais c'est littéralement le nom des fichiers du site, je me suis dis que j'allais pas changer les noms pour pas me mélanger :O ...

**Comment by t1gu1** [comment]
Oh lol, mais change ça comme je t'ai dis.

Le but n'est pas de les imiter en tout points, le but est de te faire apprendre/comprendre une bonne structure de projet avec une **BONNE** nomenclature **surtout pour les noms d'images** haha

**Comment by t1gu1** [comment]
![image](https://user-images.githubusercontent.com/12479055/89579006-080f2a80-d801-11ea-8a2d-38da65d818d6.png)

**Comment by crimsloth** [comment]
J'ai repush
