### ISSUE TITLE
Création du routeur et de la structure de dossier de base/minimum

### ISSUE THREAD

**Issue by t1gu1** [t1gu1/tp-goodfood#21]
Salut!

J'aimerais que t'ajoute un routeur au projet. (Permet de gérer et de faire changer les pages)
Ça devrait se trouver dans ton `index.js`.

J'aimerais aussi que tu crée le dossier pour la page d'accueil: `src/pages/home` avec les fichiers suivants `src/pages/home/index.js` et `src/pages/home/index.scss`.

J'aimerais que tu fasse **la même chose** avec une **page Test** (`src/pages/test`) afin de pouvoir tester si le routeur fonctionne. (Met un mini contenu comme un h1 dans le Home et dans la page Test).

---

J'aimerais aussi que tu crée le dossier `src/components/` et que tu créer la même genre de structure que pour les pages.
Il faudrait y retrouver le composant `header` et le composant `footer`. (Met un petit texte de test dans ton header et ton footer afin qu'on voir que ça fonctionne)

Il faut que tu intègres ces composants(Header & Footer) dans ton index.js
Il faut aussi que tu importe les deux pages (Home & Test)

Pour donner une idée:
```html
<Header>
<Routeur> (Va décider de quel contenu va être affiché)
<Footer>
```

J'aimerais pouvoir cliquer sur un lien qui permet de switch entre la page home et la page de test vice & versa.

Exemple: <https://reactrouter.com/web/guides/quick-start>
Mais le code séparé comme mentionné. (Dossier page pour les pages et components pour le header footer et etc)

P.S. n'oublies pas le `--save` lorsque tu installeras le paquet pour le routeur: `npm install react-router-dom --save`

**Comment by crimsloth** [comment]
reste la partie 2 à faire

**Comment by t1gu1** [comment]
J'ai remqrqué que tu avais ajouté

```html
<Header></Header>
<Routeur></Routeur>
<Footer></Footer>
```

Dans le fichier HTML.
Toutefois, c'est dans ton index.js que ça doit être ajouté.

P.S.
Header et Footer sont des components qui vont eux aussi être importé de ton dossier components.

**Comment by crimsloth** [comment]
Je vais continuer mon instruction et poursuivre ce billet par la suite.

**Comment by t1gu1** [comment]
N'oublies pas que pour les components, faudrait faire **comme les pages**.
Le nom du dossier, est le nom du composant et il y a un index.js et un index.scss à l'intérieur.

---

Autre points, peux-tu enlever `Documents` de src et le mettre à la racine du projet.
Je crois que c'est plus un dossier de documentations et de références pour t'aider.
Donc ce dossier ne doit pas se faire compiler par react et être accessible une fois l'application compilé.

**Comment by crimsloth** [comment]
> Autre points, peux-tu enlever Documents de src et le mettre à la racine du projet.
Je crois que c'est plus un dossier de documentations et de références pour t'aider.
Donc ce dossier ne doit pas se faire compiler par react et être accessible une fois l'application compilé.

Pour ça que je trouvais ça weird de le mettre dans assets lol
